# Generated by Django 6.0.3 on 2026-03-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('balance', models.IntegerField(default=10000)),
                ('voice_sample', models.FileField(blank=True, null=True, upload_to='voices/')),
                ('voice_profile_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
