# Generated by Django 6.0.3 on 2026-04-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passphrase',
            field=models.CharField(default='temp123', max_length=100),
            preserve_default=False,
        ),
    ]
