# Generated by Django 6.0.3 on 2026-03-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voice_sample',
            field=models.FileField(blank=True, null=True, upload_to='voices/'),
        ),
    ]
