# Generated by Django 6.0.3 on 2026-03-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_userprofile_voice_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voice_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
