# Generated by Django 6.0.3 on 2026-03-28 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_userprofile_voice_embedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='phone',
            new_name='receiver_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='voice_embedding',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='voice_sample',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passphrase',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(default='send_money', max_length=50),
        ),
    ]
