# Generated by Django 6.0.3 on 2026-03-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_phone_transaction_receiver_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender_phone',
            field=models.CharField(default='UNKNOWN', max_length=15),
        ),
    ]
