# Generated by Django 6.0.3 on 2026-04-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_sender_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='clickpesa_order_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='clickpesa_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='clickpesa_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
