# Generated by Django 6.0.3 on 2026-04-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_clickpesa_order_reference_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='clickpesa_status',
            new_name='provider_status',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='clickpesa_order_reference',
            new_name='provider_reference',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='clickpesa_response',
            new_name='provider_response',
        ),
        
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voice_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('send_money', 'Send Money'), ('check_balance', 'Check Balance')], default='send_money', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('awaiting_confirmation', 'Awaiting Confirmation'), ('payment_pending', 'Payment Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='awaiting_confirmation', max_length=30),
        ),
    ]
