# Generated by Django 6.0.3 on 2026-04-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='provider_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
