# Generated by Django 6.0.3 on 2026-04-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_provider_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='provider_reference',
            new_name='collection_reference',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='provider_response',
            new_name='collection_response',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='provider_status',
            new_name='collection_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
